"""Added img_path to Thread

Revision ID: 2a190fd545e0
Revises: 0199c179ca1a
Create Date: 2026-02-14 11:53:38.428996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a190fd545e0'
down_revision: Union[str, Sequence[str], None] = '0199c179ca1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('thread', sa.Column('img_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('thread', 'img_path')
    # ### end Alembic commands ###
