"""add last update

Revision ID: db6644dbe44a
Revises: 1e318ccd85ee
Create Date: 2026-02-09 12:39:19.827423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db6644dbe44a'
down_revision: Union[str, Sequence[str], None] = '1e318ccd85ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('thread', sa.Column('last_upate', sa.String(), server_default='update', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('thread', 'last_upate')
    # ### end Alembic commands ###
