"""add num_slide

Revision ID: fb89ff04db6f
Revises: 2a190fd545e0
Create Date: 2026-03-21 23:37:47.270368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb89ff04db6f'
down_revision: Union[str, Sequence[str], None] = '2a190fd545e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('thread', sa.Column('num_slide', sa.Integer(), server_default='5', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('thread', 'num_slide')
    # ### end Alembic commands ###
